### ISSUE TITLE
The status of tasks with a long execution time is lost

### ISSUE THREAD

**Issue by gordienko** [inkstak/activejob-status#10]
The status of tasks with a long run time of more than 30 minutes is lost.

Using this code did not help:
```ruby
def expiration
    @expiration ||= 60 * 60 * 24 * 30 # 30 days
end
```
How can I fix this?

**Comment by gordienko** [comment]
Probably it is necessary to define something similar during initialization?

```ruby
ActiveJob::Status.options = { expires_in: 60 * 60 * 24 * 30 } # 30 days
```
If so, write it in the documentation!

**Comment by inkstak** [comment]
README updated. Thanks !
