### ISSUE TITLE
0.2.0 is broken on Ruby 3

### ISSUE THREAD

**Issue by ahorek** [inkstak/activejob-status#14]
hey, I want to report that the new version breaks Ruby 3.0 support
```
      ArgumentError: wrong number of arguments (given 0, expected 1)
           /usr/local/rvm/gems/ruby-3.0.0-railsexpress/gems/activejob-status-0.2.0/lib/activejob-status/status.rb:22:in `update'
           /usr/local/rvm/gems/ruby-3.0.0-railsexpress/gems/activejob-status-0.2.0/lib/activejob-status.rb:17:in `block (2 levels) in <module:Status>'
```

ActiveJob::Status::Status#update method definition has been changed
https://github.com/inkstak/activejob-status/blob/51ec51d273a3490fbe811833c973aa19db26c0f4/lib/activejob-status/status.rb#L22
but keyword arguments aren't automatically converted into a hash, so this call fails since Ruby 3.0
https://github.com/inkstak/activejob-status/blob/51ec51d273a3490fbe811833c973aa19db26c0f4/lib/activejob-status.rb#L17

see https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

@inkstak ? could you take a look?

**Comment by inkstak** [comment]
Thanks for reporting it.
Fixed in 0.2.1
