### ISSUE TITLE
Can't update progress or total when the Status is initialized with a job id string

### ISSUE THREAD

**Issue by mishaschwartz** [inkstak/activejob-status#22]
Commit 82c062bb0863e21b788dff895817222dcf87aa38 sets the progress and total on the job itself as well as setting it in the storage object. 

The Status object can either be initialized with the job argument as an ActiveJob instance or with the id (string type) of an instance. This method fails if the Status is initialized with the id since strings do not have a progress attribute/setter.

For example:

```ruby
job = MyJob.perform_later

status1 = ActiveJob::Status.get(job)
status1[:progress] = 1  # this succeeds because the @job instance variable refers to the job itself

status2 = ActiveJob::Status.get(job.job_id)
status2[:progress] = 1 # this fails because the @job instance variable refers to the id of the job (a string):
                       # NoMethodError Exception: undefined method `progress' for "XXXXXXXXXXXXXXXXXXXX":String
```
 
The expected outcome is that setting the progress or total values of a Status instance should work the same no matter how the status instance is initialized (ie. the old behaviour from before this commit).

**Comment by inkstak** [comment]
I'll take a deeper look at this issue by the end of the week

**Comment by inkstak** [comment]
I'm curious : in what use case would you update the progress from outside the job?
The status was originally designed to be updated from inside the job and read from the outside.

The issue described above will be solved with the next commit, but there will always be a problem:
updating the progress from the outside won't update the already initialized `progress` object inside the job and updating progress will overwrite any progress/total set from the outside

```ruby
class SampleJob < ActiveJob::Base
  include ActiveJob::Status
  self.queue_adapter = :async

  def perform
    progress
    sleep(1)
    puts "wake up, current progress: #{progress.progress} / #{progress.total}"
    progress.finish
  end
end

job = SampleJob.perform_later
ActiveJob::Status.get(job.job_id)[:progress] = 1
ActiveJob::Status.get(job.job_id)[:total] = 5
sleep(1)
puts "status ends with #{ActiveJob::Status.get(job.job_id)}"

# ==> wake up, current progress is 0 / 100
# ==> status ends with {:status=>:completed, :progress=>100, :total=>100}

**Comment by mishaschwartz** [comment]
@inkstak Thanks for the fix!

To answer your question.... 

We have some old code that determines whether or not a job is successful if the progress and total values match. So in the case where we want that code to think the job was successful even if the job finished early we set the progress to equal the total manually. 

I completely understand how you've set it up though and I will refactor our code to not rely on progress == total as a check so that we can avoid this situation going forward.

Thanks again!

**Comment by inkstak** [comment]
Ok so even before 82c062bb0863e21b788dff895817222dcf87aa38, `progress.progress` was not updated form the outside.
You had to use `status[:progress]`. It should work again :

```ruby
class SampleJob < ActiveJob::Base
  include ActiveJob::Status
  self.queue_adapter = :async

  def perform
    progress
    sleep(1)
    puts "wake up, is it completed ? #{progress.progress == progress.total}"
    puts "try again, is it completed ? #{status[:progress] == status[:total]}"
  end
end

job = SampleJob.perform_later
ActiveJob::Status.get(job.job_id)[:progress] = 5
ActiveJob::Status.get(job.job_id)[:total] = 5

# ==> wake up, is it completed ? false
# ==> try again, is it completed ? true
```

**Comment by mishaschwartz** [comment]
That makes sense and yes we were using `status[:progress]` not `status.progress`. 
Thanks again for the fix

**Comment by inkstak** [comment]
New version released
