### ISSUE TITLE
Listing all statuses

### ISSUE THREAD

**Issue by Floppy** [inkstak/activejob-status#35]
Support question rather than bug or feature, I think. I want to show a list of recent job activity - is it possible to find *all* the available statuses?

**Comment by Floppy** [comment]
I've worked out a way to get all the keys when using a redis store at least:

```
ActiveJob::Status.store.redis.keys("activejob:status:*")
```

Won't work for other backends though.

**Comment by inkstak** [comment]
There is no support in `ActiveSupport::Cache::Store` to list all cached keys.
It's not that easy because you'll definitely have to deal with expired entries.

On another side, if you need to list statuses of the running jobs, this is what I do with Sidekiq (in a custom extension of Sidekiq::Web):

```ruby
@statuses = []

Sidekiq::WorkSet.new.each do |_pid, _tid, work|
  payload = Sidekiq.load_json(work["payload"])
  job_id = payload["args"][0]["job_id"]

  @statuses << {
    work:    work,
    status: ActiveJob::Status.get(job_id)
  }
end
```

**Comment by Floppy** [comment]
Thanks for the help - I've arrived at a solution which works for a Redis backend at least. I'll link it here in case anyone else is interested in the future! https://github.com/manyfold3d/manyfold/pull/2056
