### ISSUE TITLE
Allow to_json on ActiveStatus:Status:Status

### ISSUE THREAD

**Issue by DamianPereira** [inkstak/activejob-status#7]
I was trying to do this in a controller:

```
def status
  status = ActiveJob::Status.get(params[:job])
  render json: status.to_json
end
```

But it was not working, I've discovered I had to do `status.read.to_json`. I could also fix it by adding to_json to line 3 of status.rb. I think that should be added, or maybe add some documentation for ActiveStatus::Status::Status.read.

**Comment by inkstak** [comment]
Hi @DamianPereira 
The method `to_json` has been added to Status.
Thanks for the feedback.
