### ISSUE TITLE
Using retry_on will skips rescue_from to set status as failed 

### ISSUE THREAD

**Issue by fbbergamo** [inkstak/activejob-status#8]
The method retry_on from ActiveJob is using rescue_from. 
If a job was enqueued from a retry and failed for the last time, It will be kept as  `working` instead of `failure`.

I am using the ActiveJob adapter for Sneakers, but this looks that will happen with any adapter.

I will try to work on a solution but for now I am doing this inside my Job
```
  def perform(params)
# DOING 
    rescue Exception => e
      status.update(status: 'failed')
      raise e
    end
```

**Comment by inkstak** [comment]
Let's analyze the internal mechanisms:

```
class SampleJob < ActiveJob::Base
  def perform
    raise
  end

  # Internal implementation of include ActiveJob::Status
  before_enqueue do |job|
    job.status.update(status: :queued) 
  end

  rescue_from 'RuntimeError' do |e|
    status.update(status: :failed)
    raise e
  end

  # Internal implementation of ActiveJob#retry_on
  rescue_from 'RuntimeError' do
    retry_job(wait: 1.hour)
  end

  # Internal implementation of ActiveJob#retry_job
  def retry_job(options = {})
    enqueue options
  end
end
```

The second rescue handler (with `retry_job`) swallow the exception, so the first handler is never called and the job is never switched to "failed".

However, the `enqueue` method called by `retry_job` should requeue the same job with the same job_id.
So, the new job, with the same ID, will a fire a new `before_enqueue`, and the job status should switched back to "queued", or "working" is it start again without delay.

At least that's the way it's going to happen with Sidekiq.
The Sneakers adapter looks similar to me, the failed job is serialized with its own job_id before being requeued.

Here is a sample job to verify this behavior on Sneakers :

```
class SampleJob < ActiveJob::Base
  include ActiveJob::Status

  rescue_from 'RuntimeError' do
    new_job = retry_job(wait: 1.hour)

    # The new ID must output in your Sneakers process
    puts new_job.status.job_id
  end

  def perform
    raise
  end
end
```

```
> id = SampleJob.perform_later.job_id
 => "59d40e22-0fb4-4210-8a84-8f18f83084c1"
> ActiveJob::Status.get(id)
{:status=>:queued}
```

**Comment by inkstak** [comment]
@fbbergamo Does it answer to your problem?

**Comment by fbbergamo** [comment]
@inkstak  I will try to debug a little more maybe  could be a wrapper that its using inside the project.
 
The problem was related with the last attempt of execution that didn't changed from `working` to `failed` if the job didn't succeed  

But if this is not a general problem we could close for now

**Comment by inkstak** [comment]
Feel free to come back if you have questions :)
